apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
spec:
  chartRef:
    kind: OCIRepository
    name: nginx-repo
    namespace: flux-system
  interval: 2m
  values: